jobs:
  when:
    condition:
      not-equal: [ main, << pipeline.git.branch >> ]
  build:
    docker:
      - image: rabilrbl/aosp-build
    steps:
      - checkout
      - run:
         name: Build ROM
         command: chmod +x _build.sh && ./_build.sh